### ISSUE TITLE
Repo is outdated

### ISSUE THREAD

**Issue by oktalk** [CodeYellowBV/chartist-plugin-tooltip#3]
The current version of the chartist-plugin-tooltip (https://github.com/Globegitter/chartist-plugin-tooltip) is v0.0.12. Please update this for NPM.

Thanks.

**Comment by jackbrewer** [comment]
👍  for this please. 0.0.12 has a _lot_ of nice improvements/fixes.

**Comment by wwalser** [comment]
This will be hard to keep in sync with the parent repo since they don't really update their version number when code changes. It'll just have to be done manually from time to time I suppose.

**Comment by wwalser** [comment]
To anyone watching this issue, the origin repo has begun publishing to NPM. 
https://github.com/Globegitter/chartist-plugin-tooltip/issues/7

**Comment by Romanior** [comment]
Here is the link to actual npm module
https://www.npmjs.com/package/chartist-plugin-tooltips

@codeyellow-bv Please remove this project it is confusing and harmful for the community.

**Comment by SpaceK33z** [comment]
See #5.
