### ISSUE TITLE
Access rights to repo and npm module

### ISSUE THREAD

**Issue by Globegitter** [CodeYellowBV/chartist-plugin-tooltip#5]
Hi,

I just pushed the latest version of https://github.com/Globegitter/chartist-plugin-tooltip on npm as https://www.npmjs.com/package/chartist-plugin-tooltips because you (kindly) pushed `chartist-plugin-tooltip` already. Maybe we can close this repo, you can get access to the main repo and then we can keep the `chartist-plugin-tooltip` npm package up-to-date, rather than having two now :) Let me know. Thanks.

**Comment by Globegitter** [comment]
Or also if you have the resources to maintain the repo/package I am also happy to transfer it over to you.

**Comment by SpaceK33z** [comment]
Good idea. I don't have time for it now, but will look into it in the future.

**Comment by sarendipitee** [comment]
Seriously. Please `npm owner add` him. His repo has much more functionality. I spent so much time trying to figure out why the hell the tooltip wasn't working until I looked at the code and realized it wasn't the same.

@Globegitter I suggest you email @SpaceK33z and cc support@npmjs.com to start a name dispute process.

**Comment by SpaceK33z** [comment]
@Globegitter, you should have access to `chartist-plugin-tooltip`on npm now.

**Comment by SpaceK33z** [comment]
@Globegitter, I added you as an owner a while back, still interested in publishing it there? I am getting justice warriors on my neck here while I can't do anything about it.
